import type { Product } from '@plattform/core';

export const products: Product[] = [
  {
    id: 'go-e-gemini-flex',
    asin: 'B09V3ZH5H7',
    label: 'go-e Charger Gemini flex 11 kW',
    hint: 'Mobil & fest, PV-Überschussladen, RFID, App-Steuerung',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'aktiv',
  },
  {
    id: 'go-e-home-fix-11',
    asin: 'B082WFQKCT',
    label: 'go-e Charger HOME fix 11 kW',
    hint: 'Festinstallation, WLAN, App-Steuerung, PV-Überschuss',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'inaktiv',
  },
  {
    id: 'heidelberg-energy-control',
    asin: 'B08P4XWWZT',
    label: 'Heidelberg Energy Control 11 kW',
    hint: 'Made in Germany, integriertes Lastmanagement',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'aktiv',
  },
  {
    id: 'webasto-next',
    asin: 'B09N4VHKKW',
    label: 'Webasto Next 11 kW',
    hint: 'Bis 22 kW konfigurierbar, OTA-Updates, App-Monitoring',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'aktiv',
  },
  {
    id: 'easee-charge',
    asin: 'B0BXZ6XMZK',
    label: 'Easee Charge 11 kW',
    hint: 'Kompakteste Bauform, integrierter eSIM-Mobilfunk',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'aktiv',
  },
  {
    id: 'abl-emh1',
    asin: 'B00I3O55ZQ',
    label: 'ABL eMH1 Wallbox 11 kW',
    hint: 'Zuverlässiger Klassiker, extra langes 6,35 m Kabel',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'aktiv',
  },
  {
    id: 'abl-emh2',
    asin: 'B09ABLEMH22',
    label: 'ABL eMH2 Wallbox 11 kW',
    hint: 'Mit RFID und Lastmanagement-Schnittstelle',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'inaktiv',
  },
  {
    id: 'keba-p30-x-11',
    asin: 'B07KEBAP30X',
    label: 'KEBA P30 x-Series 11 kW',
    hint: 'RFID, MID-Zähler, Lastmanagement, österreichische Qualität',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'aktiv',
  },
  {
    id: 'keba-p30-c-22',
    asin: 'B07KEBAP30C',
    label: 'KEBA P30 c-Series 22 kW',
    hint: '22 kW, RFID, robustes Kunststoffgehäuse',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'inaktiv',
  },
  {
    id: 'mennekes-amtron-compact-11',
    asin: 'B07MENNK111',
    label: 'Mennekes Amtron Compact 11 kW',
    hint: 'RFID, Energiemessung, Made in Germany',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'aktiv',
  },
  {
    id: 'juice-charger-me3-22',
    asin: 'B07JUICE222',
    label: 'juice CHARGER me3 22 kW',
    hint: '22 kW, App, PV-Überschuss, dynamisches Lastmanagement',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'inaktiv',
  },
  {
    id: 'wallbe-eco-11',
    asin: 'B07WALLBE11',
    label: 'wallbe ECO Wallbox 11 kW',
    hint: 'Einsteigermodell, robust, OCPP-fähig',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'inaktiv',
  },
  {
    id: 'chargepoint-home-flex-11',
    asin: 'B07CHRGHFX',
    label: 'ChargePoint Home Flex 11 kW',
    hint: 'WiFi, App, flexible Ampere-Einstellung',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'inaktiv',
  },
  {
    id: 'fronius-wattpilot-11',
    asin: 'B09FRNWP11',
    label: 'Fronius Wattpilot Home 11 kW',
    hint: 'PV-Überschussladen, App, 3 Lademodi',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'aktiv',
  },
  {
    id: 'fronius-wattpilot-22',
    asin: 'B09FRNWP22',
    label: 'Fronius Wattpilot Home 22 kW',
    hint: '22 kW, PV-Überschussladen, App',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'inaktiv',
  },
  {
    id: 'wallbox-pulsar-plus-11',
    asin: 'B08WBXPP11',
    label: 'Wallbox Pulsar Plus 11 kW',
    hint: 'Kompakt, App, RFID, Bluetooth & WiFi',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'aktiv',
  },
  {
    id: 'schneider-evlink-home-11',
    asin: 'B07SCHNEV11',
    label: 'Schneider EVlink Home 11 kW',
    hint: 'Bewährte Industriequalität für die Heimanwendung',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'inaktiv',
  },
  {
    id: 'vestel-vc3-11',
    asin: 'B09VESTVC3',
    label: 'Vestel VC3 Wallbox 11 kW',
    hint: 'OCPP, App, günstiger Einstiegspreis',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'inaktiv',
  },
  {
    id: 'alfen-eve-single-pro-22',
    asin: 'B09ALFNSP2',
    label: 'Alfen Eve Single Pro-Line 22 kW',
    hint: '22 kW, OCPP, MID-Zähler, professionelle Ausstattung',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'aktiv',
  },
  {
    id: 'smappee-ev-wall-22',
    asin: 'B09SMAPEV2',
    label: 'Smappee EV Wall 22 kW',
    hint: '22 kW, dynamisches Lastmanagement, Hausenergie-Integration',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'inaktiv',
  },
];
