import type { Product } from '@plattform/core';

export const products: Product[] = [
  // ── go-e ──────────────────────────────────────────────
  {
    id: 'go-e-gemini-flex',
    asin: 'B0DKFVC2HC',
    label: 'go-e Charger Gemini flex 11 kW',
    hint: 'Mobil & fest, PV-Überschussladen, RFID, App-Steuerung',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'aktiv',
  },
  {
    id: 'go-e-home-fix-11',
    asin: '',
    label: 'go-e Charger HOME fix 11 kW',
    hint: 'Festinstallation, WLAN, App-Steuerung, PV-Überschuss',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'inaktiv',
  },
  // ── Heidelberg ────────────────────────────────────────
  {
    id: 'heidelberg-energy-control',
    asin: 'B0BCNX3T5T',
    label: 'Heidelberg Energy Control 11 kW',
    hint: 'Made in Germany, integriertes Lastmanagement',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'aktiv',
  },
  // ── Webasto ───────────────────────────────────────────
  {
    id: 'webasto-next',
    asin: 'B0CKRK7BBG',
    label: 'Webasto Next 11 kW',
    hint: 'Bis 22 kW konfigurierbar, OTA-Updates, App-Monitoring',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'aktiv',
  },
  // ── Easee ─────────────────────────────────────────────
  {
    id: 'easee-charge',
    asin: 'B0BD4Y5F8G',
    label: 'Easee Charge 11 kW',
    hint: 'Kompakteste Bauform, integrierter eSIM-Mobilfunk',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'aktiv',
  },
  // ── ABL ───────────────────────────────────────────────
  {
    id: 'abl-emh1',
    asin: 'B07XKGCPKL',
    label: 'ABL eMH1 Wallbox 11 kW',
    hint: 'Zuverlässiger Klassiker, extra langes 6,35 m Kabel',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'aktiv',
  },
  {
    id: 'abl-emh2',
    asin: 'B08QFXFFFJ',
    label: 'ABL eMH2 Wallbox 22 kW',
    hint: 'RFID, Lastmanagement-Schnittstelle, 22 kW',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'aktiv',
  },
  // ── Keba ──────────────────────────────────────────────
  {
    id: 'keba-p30-x-11',
    asin: 'B0CYHC2GWD',
    label: 'KEBA P30 x-Series 22 kW',
    hint: 'RFID, MID-Zähler, Lastmanagement, österreichische Qualität',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'aktiv',
  },
  {
    id: 'keba-p30-c-22',
    asin: '',
    label: 'KEBA P30 c-Series 22 kW',
    hint: '22 kW, RFID, robustes Kunststoffgehäuse',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'inaktiv',
  },
  // ── Mennekes ──────────────────────────────────────────
  {
    id: 'mennekes-amtron-compact-11',
    asin: 'B09SPQ57KL',
    label: 'Mennekes Amtron Compact 2.0 11 kW',
    hint: 'RFID, Energiemessung, Made in Germany',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'aktiv',
  },
  // ── Juice Technology ──────────────────────────────────
  {
    id: 'juice-charger-me3-22',
    asin: 'B00YMG2TFM',
    label: 'juice CHARGER me3 11 kW',
    hint: '11 kW, LAN, RFID, Stromzähler, Swiss made',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'aktiv',
  },
  // ── Wallbe ────────────────────────────────────────────
  {
    id: 'wallbe-eco-11',
    asin: '',
    label: 'Wallbe Eco 2.0 11 kW',
    hint: 'Einsteigermodell, robust, OCPP-fähig',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'inaktiv',
  },
  // ── ChargePoint ───────────────────────────────────────
  {
    id: 'chargepoint-home-flex-11',
    asin: '',
    label: 'ChargePoint Home Flex 11 kW',
    hint: 'WiFi, App, flexible Ampere-Einstellung',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'inaktiv',
  },
  // ── Fronius ───────────────────────────────────────────
  {
    id: 'fronius-wattpilot-11',
    asin: 'B09DG815ZD',
    label: 'Fronius Wattpilot Home 11 kW',
    hint: 'PV-Überschussladen, App, 3 Lademodi',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'aktiv',
  },
  {
    id: 'fronius-wattpilot-22',
    asin: 'B0BVZCHJ5Y',
    label: 'Fronius Wattpilot Go 22 kW',
    hint: '22 kW, PV-Überschussladen, portabel & stationär',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'aktiv',
  },
  // ── Wallbox Chargers ──────────────────────────────────
  {
    id: 'wallbox-pulsar-plus-11',
    asin: 'B08Y5KTBJ4',
    label: 'Wallbox Pulsar Plus 11 kW',
    hint: 'Kompakt, 7m Kabel, App, Bluetooth & WiFi',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'aktiv',
  },
  {
    id: 'wallbox-commander2-22',
    asin: 'B09DLCY5K4',
    label: 'Wallbox Commander 2 22 kW',
    hint: '22 kW, 7" Touchscreen, RFID, OCPP, 7 m Kabel',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'aktiv',
  },
  // ── Schneider Electric ────────────────────────────────
  {
    id: 'schneider-evlink-home-11',
    asin: 'B0CCSD136M',
    label: 'Schneider EVlink Home Smart 11 kW',
    hint: 'App, Wiser Smart Home, RFID, IP55',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'aktiv',
  },
  // ── Vestel ────────────────────────────────────────────
  {
    id: 'vestel-vc3-11',
    asin: 'B094R5YRDQ',
    label: 'Vestel EVC04 Wallbox 11 kW',
    hint: '5 m Kabel, RFID, 11 kW, günstiger Einstiegspreis',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'aktiv',
  },
  // ── Alfen ─────────────────────────────────────────────
  {
    id: 'alfen-eve-single-pro-22',
    asin: 'B08TGTPVPG',
    label: 'Alfen Eve Single Pro-Line 11 kW',
    hint: '11 kW, OCPP, MID-Zähler, professionelle Ausstattung',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'aktiv',
  },
  // ── Smappee ───────────────────────────────────────────
  {
    id: 'smappee-ev-wall-22',
    asin: '',
    label: 'Smappee EV Wall 22 kW',
    hint: '22 kW, dynamisches Lastmanagement, Hausenergie-Integration',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'inaktiv',
  },
  // ── Tesla ─────────────────────────────────────────────
  {
    id: 'tesla-wall-connector-gen3',
    asin: 'B0BW16BBKQ',
    label: 'Tesla Wall Connector Gen. 3 22 kW',
    hint: 'Bis 22 kW, Typ-2, WiFi, auch für Nicht-Tesla geeignet',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'aktiv',
  },
  // ── myenergi ──────────────────────────────────────────
  {
    id: 'myenergi-zappi-22',
    asin: 'B092R9CRBG',
    label: 'myenergi Zappi 22 kW',
    hint: '22 kW, PV-Überschussladen, Hub-kompatibel',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'aktiv',
  },
  // ── Autel ─────────────────────────────────────────────
  {
    id: 'autel-maxicharger-22',
    asin: 'B0BXLXLRG5',
    label: 'Autel MaxiCharger AC 22 kW',
    hint: '22 kW, RFID, WiFi, App, OCPP 1.6',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'aktiv',
  },
  // ── Morec ─────────────────────────────────────────────
  {
    id: 'morec-wallbox-11',
    asin: 'B0CP5X2ZQ4',
    label: 'Morec Wallbox 11 kW',
    hint: '11 kW, 6 m Kabel, Typ 2, Preis-Leistungs-Tipp',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'aktiv',
  },
  // ── Huawei ────────────────────────────────────────────
  {
    id: 'huawei-scharger-22',
    asin: 'B0D58MXQPJ',
    label: 'Huawei Smart Charger 22 kW',
    hint: '22 kW, WLAN, RFID, FusionSolar-Integration',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'aktiv',
  },
  // ── Anker ─────────────────────────────────────────────
  {
    id: 'anker-solix-v1-11',
    asin: 'B0FNCWMVT9',
    label: 'Anker SOLIX V1 Wallbox 11 kW',
    hint: '11 kW, WLAN, Bluetooth, PV-Integration, App',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'aktiv',
  },
  // ── Elli (VW Group) ───────────────────────────────────
  {
    id: 'elli-charger2-connect-11',
    asin: 'B0DQ96YJMR',
    label: 'Elli Charger 2 Connect 11 kW',
    hint: 'VW Group, 11 kW, RFID, App, MID-Zähler, LAN/WLAN',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'aktiv',
  },
  {
    id: 'elli-charger2-pro-22',
    asin: 'B0DQ8X19HT',
    label: 'Elli Charger 2 Pro 22 kW',
    hint: '22 kW, RFID, MID, OCPP 2.0.1, LAN/WLAN/SIM+',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'aktiv',
  },
  {
    id: 'elli-wallbox-standard-11',
    asin: 'B0C1N1NXW5',
    label: 'Volkswagen Elli Wallbox Standard 11 kW',
    hint: '11 kW, 7,5 m Kabel, VW OEM, alle E-Autos',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'aktiv',
  },
  // ── SMA ───────────────────────────────────────────────
  {
    id: 'sma-ev-charger-22',
    asin: 'B0D9C73JSP',
    label: 'SMA EV Charger 22 kW',
    hint: '22 kW, Sunny Home Manager, PV-Überschuss, 7,5 m Kabel',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'aktiv',
  },
  // ── Kostal ────────────────────────────────────────────
  {
    id: 'kostal-enector-11',
    asin: '',
    label: 'Kostal Enector 11 kW',
    hint: '11 kW, Plenticore-Integration, PV-Überschuss',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'inaktiv',
  },
  // ── Sungrow ───────────────────────────────────────────
  {
    id: 'sungrow-ac011e-11',
    asin: '',
    label: 'Sungrow AC011E Wallbox 11 kW',
    hint: '11 kW, OCPP, App, Sungrow-Wechselrichter-Integration',
    checked: '2026-09-28',
    type: 'produkt',
    status: 'inaktiv',
  },
];
